pub mod transform;
pub mod rigidbody;
pub mod collider;
pub mod renderable;
pub mod force_field;
pub mod tags;
pub mod role;
pub mod lifetime;
pub mod game_state;
pub mod behavior;
pub mod physics_material;
pub mod impulse;
pub mod motion_constraint;
pub mod zone_effect;
pub mod property_tween;
pub mod entity_flash;
pub mod ghost_trail;
pub mod time_scale;
pub mod active;
pub mod waypoint_path;
pub mod signal;
pub mod hierarchy;
pub mod state_machine;
pub mod coroutine;
pub mod sprite_animator;
pub mod physics_joint;
pub mod resource_inventory;
pub mod graph_node;
pub mod visual_connection;

pub use transform::Transform;
pub use rigidbody::RigidBody;
pub use collider::{Collider, ColliderShape};
pub use renderable::{Renderable, Visual};
pub use force_field::{ForceField, FieldType, Falloff};
pub use tags::Tags;
pub use role::Role;
pub use lifetime::Lifetime;
pub use game_state::GameState;
pub use behavior::{Behavior, BehaviorMode};
pub use physics_material::PhysicsMaterial;
pub use impulse::Impulse;
pub use motion_constraint::MotionConstraint;
pub use zone_effect::{ZoneEffect, ZoneEffectKind};
pub use property_tween::PropertyTween;
pub use entity_flash::EntityFlash;
pub use ghost_trail::GhostTrail;
pub use time_scale::TimeScale;
pub use active::Active;
pub use waypoint_path::WaypointPath;
pub use signal::{SignalEmitter, SignalReceiver};
pub use hierarchy::{Parent, Children, WorldTransform};
pub use state_machine::StateMachine;
pub use coroutine::Coroutine;
pub use sprite_animator::SpriteAnimator;
pub use physics_joint::PhysicsJoint;
pub use resource_inventory::ResourceInventory;
pub use graph_node::GraphNode;
pub use visual_connection::VisualConnection;

/// Trait for components to provide their own schema metadata.
pub trait SchemaInfo {
    fn schema_name() -> &'static str;
    fn schema() -> serde_json::Value;
}
